### ISSUE TITLE
Control overall width of table

### ISSUE THREAD

**Issue by John02139** [HugoPGomes/pgf-periodictable#6]
Is there a simple way to set the periodic table to text width, column width, etc.?  I have not been able to find this in the manual (or in the recent TUGBoat article).

**Comment by HugoPGomes** [comment]
Yes there is. It can be done using the `\resizebox` command provided by the graphicx package (and also by the graphics package).

For example:
```tex
\resizebox{\linewidth}{!}{\pgfPT}
```
or
```tex
\resizebox{\linewidth}{!}{\pgfPT[show title=false]}
```
will produce a Periodic Table with the width of the current `\linewidth`, whatever is its value (the text width, the column width, the width of a minipage,...), and with the proper scaling of its height.

There is no need of loading the graphicx package since pgf-PeriodicTable loads the tikz package, which in turn loads the graphicx package.

Best regards

**Comment by John02139** [comment]
Beautiful!  Works very well.  May I suggest to include this information in the documentation?

Cheers, John

**Comment by HugoPGomes** [comment]
Hi John,
An update to pgf-PeriodicTable (v2.1.5 - 2025/02/10) has been submitted to
CTAN and the information has been included.
Thanks again,
Hugo Gomes

John ***@***.***> escreveu (domingo, 17/11/2024 à(s) 16:21):
